### ISSUE TITLE
No valid output using bellhopcuda v1.41

### ISSUE THREAD

**Issue by lcarrieri-ilstudio** [A-New-BellHope/bellhopcuda#33] opened 2024-06-20 09:18 UTC
Greetings,
I am doing a test simulation using the `bellhopcuda` executable available in the latest release (v1.41) with a 2D environment that includes both bottom reflection coefficients and bathymetry; all the files are attached to this issue as `.txt` files):

- [test_run_brc.txt](https://github.com/user-attachments/files/15911535/test_run_brc.txt)
- [test_run_bty.txt](https://github.com/user-attachments/files/15911536/test_run_bty.txt)
- [test_run_env.txt](https://github.com/user-attachments/files/15911537/test_run_env.txt)

When running an incoherent transmission loss run, however, `bellhopcuda.exe` doesn't seem to output a `.shd` file with valid data, in the sense that when the binary file is read by `plotshd.m` or `readshd.m` there is no data.

Can you please tell me where the issue is?
Many thanks

**Comment by oldstylejoe** [comment] 2024-06-20 17:43
Thanks for trying bellhopcuda! The env files you shared work ok for me on bellhopcuda and fortran bellhop. Is it possible you're using the 2023 version of the Acoustics Toolbox for the plotting routines? Bellhopcuda is based on the 2022 version, and there are some breaking changes in 2023 (the float size in the shd files changed).
If that's the case, you can get the 2022 version here - http://oalib.hlsresearch.com/AcousticsToolbox/at_2022_4_20.zip

**Comment by lcarrieri-ilstudio** [comment] 2024-06-21 15:15
Yes, that solved the issue, thank you!
I have another question: I was also trying to impose beam displacement in the `.env` file by adding **'S'** to the **'IB'** part, but when I read the log in the `.prt` file it says _No beam shift in effect_ . Is beam displacement implemented in `bellhopcuda`?

**Comment by oldstylejoe** [comment] 2024-06-21 20:49
Glad to be of help:)
For the beam shift, I'm not able to reproduce the issue. If I make line 123 `'IB    S'`, then both oalib bellhop and bellhopcuda use beam shift mode, or at least say so in the prt file.
If this is not as expected, then please create a new issue. I'll close this one in a few hours.

**Closed** 2024-06-24 21:35 UTC
